# Generated by Django 2.1.7 on 2019-03-28 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Signup_Form',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(verbose_name='appointment submitted')),
                ('name', models.CharField(max_length=200)),
                ('email', models.CharField(max_length=50)),
                ('number', models.CharField(max_length=12)),
            ],
        ),
    ]
