# Generated by Django 2.1.7 on 2019-03-28 15:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('signup', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='signup_form',
            name='time',
        ),
    ]
