# Generated by Django 2.1.7 on 2019-03-28 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signup', '0002_remove_signup_form_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='signup_form',
            name='dob',
            field=models.CharField(default='00/00/0000', max_length=200),
        ),
        migrations.AddField(
            model_name='signup_form',
            name='last_employment',
            field=models.CharField(default='none', max_length=200),
        ),
        migrations.AddField(
            model_name='signup_form',
            name='role',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
