# Generated by Django 2.1.7 on 2019-03-28 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signup', '0003_auto_20190328_2036'),
    ]

    operations = [
        migrations.AddField(
            model_name='signup_form',
            name='criminal',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='signup_form',
            name='resume',
            field=models.FileField(null=True, upload_to='resumes/'),
        ),
    ]
