# Generated by Django 2.1.7 on 2019-03-28 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signup', '0004_auto_20190328_2039'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='signup_form',
            name='resume',
        ),
        migrations.AlterField(
            model_name='signup_form',
            name='criminal',
            field=models.BooleanField(),
        ),
    ]
