# Generated by Django 2.1.7 on 2019-03-28 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signup', '0005_auto_20190328_2043'),
    ]

    operations = [
        migrations.AddField(
            model_name='signup_form',
            name='resume',
            field=models.FileField(null=True, upload_to='resumes/'),
        ),
    ]
